apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sam-image-encoder-predictor-logger
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sam-image-encoder-transformer-logger
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sam-image-encoder
spec:
  predictor:
#    nodeSelector:
#      cloud.google.com/gke-accelerator: nvidia-tesla-t4
    model:
      modelFormat:
        name: triton
      storageUri: pvc://model-pv-claim/sam_image_encoder.tgz
#      storageUri: gs://cw-ml-models/triton/models/sam_image_encoder.tgz
      runtimeVersion: 23.03-py3
      ports:
        - name: h2c
          protocol: TCP
          containerPort: 9000
      resources:
        limits:
          cpu: 6
          memory: 12Gi
        requests:
          cpu: 6
          memory: 12Gi
#      resources:
#        limits:
#          nvidia.com/gpu: 1
#        requests:
#          nvidia.com/gpu: 1
    logger:
      mode: all
      url: http://sam-image-encoder-predictor-logger.default/
  transformer:
    containers:
      - image: nhm0819/sam_image_transformer:latest
#      - image: gcr.io/crowdworks-aiml-ops/sam_image_transformer:v0.0
        name: sam_image_encoder
        command:
          - "python"
          - "transformer.py"
        args:
          - --model_name
          - sam_image_encoder
          - --protocol
          - grpc-v2
        resources:
          limits:
            cpu: 0.5
            memory: 1Gi
          requests:
            cpu: 0.5
            memory: 1Gi
    logger:
      mode: all
      url: http://sam-image-encoder-transformer-logger.default/